version: '3.8'

services:
  frontend:
    build:
       context: ./src/frontend
       dockerfile: dev.Dockerfile
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    command: >
      sh -c "
      if [ -f yarn.lock ]; then yarn dev;
      elif [ -f package-lock.json ]; then npm run dev;
      elif [ -f pnpm-lock.yaml ]; then pnpm dev;
      else npm run dev;
      fi
      "

  backend:
    build:
      context: .
      dockerfile: ./src/backend/dev.Dockerfile
    working_dir: /app
    volumes:
      - ./src/backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn index:app --host 0.0.0.0 --port 8000 --reload

