version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend/dev.Dockerfile
    working_dir: /app
    volumes:
      - ./src/backend:/app
      - ./src/backend/data:/app/data:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn index:app --host 0.0.0.0 --port 8000 --reload

volumes:
  frontend-node-modules:
  frontend-build:
  backend-data:
