repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: .*\.py$
      - id: end-of-file-fixer
        files: .*\.py$
      - id: trailing-whitespace
        files: .*\.py$
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: .*\.py$
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        files: .*\.py$

